name: music_player
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

  # ----------------------------- PACKAGES ----------------------------- #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^2.6.1
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1

  # Icons
  iconsax_flutter: ^1.0.1
  cupertino_icons: ^1.0.8

  # API Integration
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  google_sign_in: ^7.2.0

  # Local Storage
  sqflite: ^2.4.1
  path: ^1.9.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.4

  # Audio Player
  just_audio: ^0.9.42
  flutter_inappwebview: ^6.0.0

  # State Management
  get: ^4.7.2
  flutter_dotenv: ^6.0.0

  # Spotify Integration
  oauth2: ^2.0.2
  app_links: ^6.3.1 
  
  # Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Serialization
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  crypto: ^3.0.6
  
  # Environment Variables
  uuid: ^4.5.1
  flutter_facebook_auth: ^7.1.2
  sqflite_common_ffi: ^2.3.6
  sqflite_common_ffi_web: ^1.0.0
  firebase_analytics: ^12.0.4
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  shimmer: ^3.0.0
  google_mobile_ads: ^5.2.0
  spotify_sdk: ^3.0.2

  # ----------------------------- PACKAGES END ----------------------------- #

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true


 # ----------------------------- ASSETS ----------------------------- #
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - .env
    
  # ----------------------------- FONTS ----------------------------- #
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logos/flashback.jpeg
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/logos/flashback.jpeg

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logos/flashback.jpeg
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: assets/logos/flashback.jpeg
    
